Block:
  InstanceId: 12345678-9012-3456-7890-123456789012

deployments:
  kubernetes:
    variables:
      domain: nearbycomputing.com
      appname: monit
      alerta:
        enabled: true
        port: 9272
        image:
          name: alerta/alerta-web
          tag: 8.2.0
        service:
          port: 8080
        admin:
          user: admin@alerta.io
          password: alerta
        postgresql:
          persistence:
            enabled: false
            size: 10Gi
      grafana:
        enabled: true
        image:
          name: registry.nearbycomputing.com/external/grafana/grafana
          tag: 8.2.5
        admin:
          user: admin
          password: password
        service:
          type: NodePort
          port: 80
          nodePort: 30007
      prometheus:
        enabled: true
        services:
          alertmanager:
            enabled: true
            persistentVolume:
              enabled: false
            image:
              repository: quay.io/prometheus/alertmanager
              tag: v0.23.0
          kubeStateMetrics:
            enabled: true
          nodeExporter:
            enabled: true
            image:
              repository: quay.io/prometheus/node-exporter
              tag: v1.3.0
          server:
            enabled: true
            image:
              repository: quay.io/prometheus/prometheus
              tag: v2.31.1
            persistentVolume:
              enabled: false
          pushgateway:
            enabled: true
            image:
              repository: prom/pushgateway
              tag: v1.4.2
      cloudprober:
        enabled: true
        image:
          repository: registry.nearbycomputing.com/external/cloudprober
          pullPolicy: IfNotPresent
          tag: "latest"
        service:
          annotations:
            prometheus.io/scrape: "true"
          type: ClusterIP
          port: 9313
        probes:
          latencyProbes:
            name: "latency-probes"
            latency_unit: "ms"
            interval_msec: 15000
            timeout_msec: 1000
            use_datagram_socket: false
            targets:
              - "8.8.8.8"
              - "8.8.4.4"
              - "1.1.1.1"
              - "www.google.com"
    configuration:
      chart:
        repo: https://registry.nearbycomputing.com/chartrepo/apps
        version: 0.1.3
        name: monitoring

placement:
  site:
    label: f64193a2-32b6-4c6b-a668-a0e6394ae9a9
