apiVersion: blocks/v1beta1
kind: ChartDeployment
metadata:
  name: phase1-{{ .Values.deployments.complexExample.variables.appname }}
  namespace: {{ .Values.Block.InstanceId }}
spec:
  template:
    metadata:
      labels:
        application: {{ .Values.deployments.complexExample.variables.appname }}-{{ .Values.Block.InstanceId }}
    spec:
      k8sClusterSelector:
        matchLabels:
          site.nbycomp.com/{{ .Values.placement.site.label }}: "true"
      chart: {{ .Values.deployments.complexExample.configuration.chart.name }}
      version: {{ .Values.deployments.complexExample.configuration.chart.version }}
      repo:
        url: {{ .Values.deployments.complexExample.configuration.chart.repo }}
      values: |
        service:
          type: ClusterIP
        serverBlock: |-
          server {
            listen 0.0.0.0:8080;
            add_header Content-Type text/html;
            location / {
              return 200 "hello World! Phase1 nginx chart release running";
            }
          }
