apiVersion: blocks/v1beta1
kind: ConnectionSet
metadata:
  name: ready-rel-{{ .Values.deployments.complexExample.variables.appname }}-{{ .Values.Block.InstanceId }}
spec:
  targetListSelector:
    kind: ChartRelease
    matchLabels:
      application: {{ .Values.deployments.complexExample.variables.appname }}-{{ .Values.Block.InstanceId }}
  template:
    metadata:
      labels:
        # This label is used by `phase2-chart-deployment.yaml`
        application: ready-phase1-{{ .Values.deployments.complexExample.variables.appname }}-{{ .Values.Block.InstanceId }}
    spec:
      value: |
        name: {{`{{ .Target.metadata.name }}`}}
        cluster: {{`{{ .Target.spec.k8sClusterName }}`}}
        createdAt: {{`{{ .Target.metadata.creationTimestamp }}`}}
