apiVersion: blocks/v1beta1
kind: ChartDeployment
metadata:
  name: nginx-deployment
  namespace: 12345678-9012-3456-7890-123456789012
spec:
  connectionListSelectors:
    placement:
      matchLabels:
        application: another-sample-application
        kind: placement
      limit: 1
  template:
    metadata:
      labels:
        application: nginx-sample-application
    spec:
      k8sClusterSelector:
        matchLabels:
          "{{`{{ .Connections.placement.site }}`}}": "true"
      chart: nginx
      repo:
        url: https://charts.bitnami.com/bitnami
      version: 13.2.33
      values: |
        service:
          type: NodePort
          port: 80
          httpsPort: 443
          nodePorts:
            http: "31080"
            https: "31443"
