apiVersion: blocks/v1beta1
kind: K8sCluster
metadata:
  name: default-cluster
spec:
  kubeConfig:
    secretKeyRef:
      key: kubeconfig
      name: kubeconfig-default-cluster
  managedNamespace: 12345678-9012-3456-7890-123456789012
