apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-b0ff2cb6-8302-4530-a929-aedd7b1ff33e
  namespace: default
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: <ca>
        server: https://b0ff2cb6-8302-4530-a929-aedd7b1ff33e:6443
      name: b0ff2cb6-8302-4530-a929-aedd7b1ff33e
    contexts:
    - context:
        cluster: b0ff2cb6-8302-4530-a929-aedd7b1ff33e
        user: admin
      name: admin
    current-context: admin
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        client-certificate-data: <cert>
        client-key-data: <key>
type: Opaque
