apiVersion: blocks/v1beta1
kind: Connection
metadata:
  name: k8sclusters-site-{{ .Values.placement.site.label }}
  labels:
    site.nbycomp.com/{{ .Values.placement.site.label }}: "true"
    kind: K8sCluster
spec:
  targetReference: 
    kind: ChartRelease
    name: nginx-deployment-6nchd
    namespace: 12345678-9012-3456-7890-123456789012
  value: |
    clusterName: {{`{{ .Target.spec.k8sClusterName }}`}}
