apiVersion: blocks/v1beta1
kind: ConnectionSet
metadata:
  name: k8sclusters-customerSiteA
spec:
  targetListSelector:
    kind: ChartRelease
    matchLabels:
      site.nbycomp.com/customerSiteA: "true"
  template:
    metadata:
      labels:
        site.nbycomp.com/customerSiteA: "true"
        kind: ChartRelease
    spec:
      value: |
        connectionInfo: any value here
