apiVersion: blocks/v1beta1
kind: ConnectionSet
metadata:
  name: k8sclusters-customerSiteA
spec:
  targetListSelector:
    kind: VMInstance
    matchLabels:
      site.nbycomp.com/customerSiteA: "true"
  template:
    metadata:
      labels:
        site.nbycomp.com/customerSiteA: "true"
        kind: VMInstance
    spec:
      value: |
        clusterName: {{`{{ .Target.spec.vmClusterName }}`}}
