apiVersion: blocks/v1beta1
kind: ChartDeployment
metadata:
  name: nginx-deployment
  namespace: {{ .Values.Block.InstanceId }}
spec:
  template:
    spec:
      k8sClusterSelector:
        matchLabels:
          site.nbycomp.com/{{ .Values.placement.site.label }}: "true"
      chart: {{ .Values.deployments.simpleExample.configuration.chart.name }}
      version: {{ .Values.deployments.simpleExample.configuration.chart.version }}
      repo:
        url: {{ .Values.deployments.simpleExample.configuration.chart.repo }}
