apiVersion: blocks/v1beta1
kind: ChartRelease
metadata:
  name: nginx-deployment-6nchd
  namespace: 12345678-9012-3456-7890-123456789012
spec:
  k8sClusterName: e40990f8-8f55-4d02-90d0-462c48434286
  chart: nginx
  repo:
    url: https://private.example.com/charts
    username: user
    password:
      secretKeyRef:
        name: secretName
        key: secretKey
  version: 13.2.33
  values: |
    service:
      type: NodePort
      port: 80
      httpsPort: 443
      nodePorts:
        http: "31080"
        https: "31443"
