apiVersion: blocks/v1beta1
kind: ChartRelease
metadata:
  name: nginx-deployment-6nchd
  namespace: 12345678-9012-3456-7890-123456789012
spec:
  k8sClusterSelector:
    matchLabels:
      site.nbycomp.com/customerSiteA: "true"
  chart: nginx
  repo:
    url: https://charts.bitnami.com/bitnami
  version: 11.1.5
  values: |
    service:
      type: NodePort
      port: 80
      httpsPort: 443
      nodePorts:
        http: "31080"
        https: "31443"
