apiVersion: blocks/v1beta1
kind: ChartRelease
metadata:
  labels:
    application: nginx-sample-application
  name: nginx-deployment-6nchd
  namespace: 12345678-9012-3456-7890-123456789012
spec:
  chart: nginx
  k8sClusterSelector:
    matchLabels:
      site.nbycomp.com/customerSiteA: "true"
  repo:
    url: https://charts.bitnami.com/bitnami
  version: 11.1
  rolloutStrategy:
    crontab:
      # rollout by end of Q1 and Q4
      - schedule: "0 3 31 3,12 *"
        timeZone: UTC
      # rollout by end of Q2 and Q3
      - schedule: "0 3 30 6,9 *"
        timeZone: UTC
    startingDeadlineSeconds: 3600
  values: |
    service:
      type: NodePort
      port: 80
      httpsPort: 443
      nodePorts:
        http: "31080"
        https: "31443"
